name: kluge
favicon: null
layout_spectrum: 0.9403272720519453
typography_spectrum: 0.8369990375358611
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.0005411074962466955
  lightness: 0.0860429632011801
  saturation: 0.8696415252052248
  rhythmicContrast: 0.5847654994577169
purpose: []
